experiment_name: r18-imagenet100
data_path: data/imagenet-100
dataset: imagenet100 
arch: resnet18
weight_init: default
batch_size: 32
lr: 0.1
momentum: 0.9  
nesterov: False 
weight_decay: 0.0001
epochs: 90
schedule: step
steps: [40,80]
step_size: 0.1

