experiment_name: cifar10-mixup-aa-ls-cutout-ranger  
outpt_dir: drive/My Drive/output/
dataset: cifar10
transforms: autoaugment_cutout
training: mixup
smoothing: 0.1
epochs: 600
schedule: flatcosine
flat_rate: 0.75
optimizer: ranger
beta1: 0.95
beta2: 0.999
lr: 0.001

